# Generated by Django 3.2.6 on 2021-08-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('followers', models.ManyToManyField(blank=True, related_name='entreprises_followed', to='user_core.CustomUser')),
                ('likes', models.ManyToManyField(blank=True, related_name='entreprises_liked', to='user_core.CustomUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_core.customuser')),
            ],
        ),
    ]
